version: "3"

services:
  main-service-db:
    image: postgres
    ports:
      - 6001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_app
  events-service-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: events
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672